#! /bin/sh

echo "## FIREWALL  ##"

export IF_PRIVATE=br0
export SN_PRIVATE=192.168.1.0/255.255.255.255

export IF_PUBLIC=red0
export SN_PUBLIC=0.0.0.0/255.255.255.255

echo " -> PRIVATE: $IF_PRIVATE $SN_PRIVATE"
echo " -> PUBLIC:  $IF_PUBLIC $SN_PUBLIC"
