#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Simon Baur <sbausis@gmx.net>
# @copyright Copyright (c) 2015 Simon Baur
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SERVICE_XPATH_NAME="firewall"
SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

case "$1" in
    configure)

        # Check for XML config
        if ! omv_config_exists "${SERVICE_XPATH}"; then
			omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}" ""
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/enable"; then
			omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
        fi

        omv-mkconf firewall 2>/dev/null

        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
